import { Inter } from "next/font/google";
import "./globals.css";
import RootHeader from "./RootHeader";
import RootSideMenu from "./RootSideMenu";
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapBundleJS from "./BootstrapBundleJS";
import AppContextProvider from "./states/context/AppContextProvider";
import StoreProvider from "./states/redux/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BootstrapBundleJS />
          <StoreProvider>
          <AppContextProvider>
            <div className="d-flex flex-column vh-100">
              <RootHeader />
              <div className="flex-grow-1 container-fluid">
                <div className="row h-100">
                  <div className="col-md-6 col-lg-4 bg-dark">
                    <div className=" h-100 d-flex flex-column">
                      <div className="flex-grow-1" style={{ height: "0px", overflowY: "auto", overflowX: "hidden" }}>
                        <RootSideMenu />
                      </div>
                    </div>
                  </div>
                  <div className="col-md-6 col-lg-8 p-3">
                    <div className=" h-100 d-flex flex-column">
                      <div className="flex-grow-1 overflow-auto pe-3" style={{ height: "0px" }}>
                        {children}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </AppContextProvider>
          </StoreProvider>
      </body>
    </html>
  );
}
